from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics
from reportlab.lib import colors

def generate_pdf(client_name, client_input, model, estimated_cost, budget_result):
    """Generates a professional quotation PDF with proper design and spacing."""
    
    # Register font that supports ₹
    pdfmetrics.registerFont(TTFont('DejaVu', 'DejaVuSans.ttf'))  # ensure DejaVuSans.ttf is available
    
    # Create PDF file path
    file_path = f"quotation_{client_name.replace(' ', '_')}.pdf"
    c = canvas.Canvas(file_path, pagesize=A4)
    width, height = A4
    
    # Title
    c.setFont("DejaVu", 22)
    c.setFillColor(colors.darkblue)
    c.drawString(50, height - 50, "Software Project Quotation")
    
    # Horizontal line below title
    c.setStrokeColor(colors.darkblue)
    c.setLineWidth(1)
    c.line(50, height - 55, width - 50, height - 55)
    
    # Starting Y position
    y = height - 90
    line_spacing = 25
    
    # Client & Project Information
    c.setFont("DejaVu", 14)
    c.setFillColor(colors.black)
    c.drawString(50, y, "Client & Project Information:")
    y -= line_spacing
    
    c.setFont("DejaVu", 12)
    c.drawString(70, y, f"Client Name: {client_name}")
    y -= line_spacing
    c.drawString(70, y, f"Project Name: {client_input['project_name']}")
    y -= line_spacing
    c.drawString(70, y, f"Domain: {client_input['domain']}")
    y -= line_spacing
    c.drawString(70, y, f"Recommended Model: {model}")
    y -= line_spacing
    c.drawString(70, y, f"Estimated Cost: ₹{estimated_cost}")
    y -= line_spacing
    
    # Budget Status with color
    c.setFont("DejaVu", 14)
    if budget_result["within_budget"]:
        c.setFillColor(colors.green)
    else:
        c.setFillColor(colors.red)
    c.drawString(50, y, f"Budget Status: {budget_result['message']}")
    y -= line_spacing
    
    # Optimization Suggestions (if over budget)
    if not budget_result["within_budget"] and budget_result.get("suggestions"):
        c.setFillColor(colors.darkblue)
        c.setFont("DejaVu", 14)
        c.drawString(50, y, "Optimization Suggestions:")
        y -= line_spacing
        
        c.setFont("DejaVu", 12)
        c.setFillColor(colors.black)
        for s in budget_result["suggestions"]:
            # Wrap long suggestions manually if needed
            if len(s) > 80:
                wrapped_lines = [s[i:i+80] for i in range(0, len(s), 80)]
                for line in wrapped_lines:
                    c.drawString(70, y, f"• {line}")
                    y -= line_spacing
            else:
                c.drawString(70, y, f"• {s}")
                y -= line_spacing
    
    # Footer line
    c.setStrokeColor(colors.gray)
    c.setLineWidth(0.5)
    c.line(50, 50, width - 50, 50)
    
    # Footer text
    c.setFont("DejaVu", 10)
    c.setFillColor(colors.gray)
    c.drawString(50, 35, "Generated by Project Quotation Tool")
    
    # Save PDF
    c.save()
    return file_path