from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
import os
from datetime import datetime


def generate_pdf(client_name, input_data, model, estimated_cost, budget_result, file_path="quotation.pdf"):
    """
    Generates a quotation PDF for the project.

    Parameters:
        client_name (str): Name of the client.
        input_data (dict): Input details provided by the client.
        model (str): Suggested software development model.
        estimated_cost (int): Estimated cost in INR.
        budget_result (dict): Result from budget_optimizer.
        file_path (str): Output path of the PDF file.

    Returns:
        str: Path to the generated PDF.
    """
    c = canvas.Canvas(file_path, pagesize=A4)
    width, height = A4

    # Title
    c.setFont("Helvetica-Bold", 18)
    c.drawCentredString(width / 2, height - 60, "Project Quotation Summary")

    # Basic Info
    c.setFont("Helvetica", 12)
    y = height - 100
    c.drawString(50, y, f"Client Name: {client_name}")
    c.drawString(300, y, f"Date: {datetime.now().strftime('%d-%m-%Y')}")
    y -= 20

    # Input Data
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Project Details:")
    y -= 20
    c.setFont("Helvetica", 12)
    for key, value in input_data.items():
        c.drawString(60, y, f"{key.capitalize()}: {value}")
        y -= 18

    # Suggested Model
    y -= 10
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Suggested Development Model:")
    y -= 20
    c.setFont("Helvetica", 12)
    c.drawString(60, y, f"{model}")
    y -= 30

    # Cost Info
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Estimated Cost:")
    y -= 20
    c.setFont("Helvetica", 12)
    c.drawString(60, y, f"₹{estimated_cost}")
    y -= 30

    # Budget Result
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Budget Analysis:")
    y -= 20
    c.setFont("Helvetica", 12)
    c.drawString(60, y, budget_result["message"])
    y -= 20

    if not budget_result["within_budget"]:
        c.setFont("Helvetica-Bold", 12)
        c.drawString(60, y, "Suggestions to optimize:")
        y -= 16
        c.setFont("Helvetica", 12)
        for suggestion in budget_result["suggestions"]:
            c.drawString(70, y, f"- {suggestion}")
            y -= 16

    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 30, "Generated by Software Model Recommender | For Industrial Use")

    c.save()
    return file_path